/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
    `java-gradle-plugin`
}

val asmVersion by extra { "9.6" }

dependencies {
    implementation("org.ow2.asm:asm:$asmVersion")
}

repositories {
    gradlePluginPortal()
}
