/*
 *    Copyright (c) 2023-2026.  lWoHvYe(Hongyan Wang)
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    signing
}

group = "com.lwohvye"
version = "4.8.4-chi"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

publishing {
    repositories.maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/lWoHvYe/unicorn")
        credentials {
            username = providers.gradleProperty("gpr.user")
                .orElse(providers.environmentVariable("USERNAME"))
            password = providers.gradleProperty("gpr.key")
                .orElse(providers.environmentVariable("TOKEN"))
        }
    }
}

signing {
    isRequired = !version.toString().endsWith("-SNAPSHOT") && System.getenv("CI") == null
    sign(publishing.publications)
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.addAll(listOf("--enable-preview", "-parameters"))
}

// Preview features affect both compilation and execution. Keep the runtime
// configuration aligned with JavaCompile so tests and JavaExec tasks can load
// classes compiled with --enable-preview.
tasks.withType<Test>().configureEach {
    jvmArgs("--enable-preview")
}

tasks.withType<JavaExec>().configureEach {
    jvmArgs("--enable-preview")
}
