name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue_message: "Greetings for the day! Thanks for your issue, will feedback soon"
        pr_message: "Greetings for the day! Thanks for your pr, will feedback soon"
