name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Greetings for the day! Thanks for your issue, will feedback soon"
        pr-message: "Greetings for the day! Thanks for your pr, will feedback soon"
